#!/usr/bin/env python3
"""
Remediator — generates a fix for what Investigator found, validates it
deterministically, and opens a real pull request (US-3). Design:
docs/decisions/0008-remediator-design.md. Read that file for the full
reasoning — this module implements it, not re-derives it.

The core judgment call this module embodies, stated plainly (the repo
owner's own words, worth repeating here rather than only in the design
doc): **quarantine suspect rows, never silently correct them.** The
tempting fix for a sign-flip is `ABS(billing_amount)` — negatives become
positive, the anomaly disappears, the demo looks clean. Rejected: we don't
actually know *why* the flip happened, and in health insurance, silently
"fixing" financial data you don't understand is exactly how a data team
creates the next wrongful-denial incident while erasing the evidence of
this one. A dead-letter quarantine table says: clean rows flow, suspect
rows get surfaced for a human, nothing is invented. Same evidence
discipline as Investigator refusing to assume a root cause it hasn't
verified — Guardian never pretends to know more than the evidence
supports.

Two fix shapes, chosen by `InvestigatorFinding.primary_root_cause`, both
applied to the SAME simulated pipeline-owner repo
(~/projects/denial-guardian-data-platform) but at different files:

  - `introduced_at:X` — the defect first appears at X's own build. Fix
    modifies X's transform file directly (e.g. transform/claims.sql):
    split the build into a clean table and an `X_quarantine` table.
  - `inherited_from:X` — the defect is already present in the earliest
    available data (X, e.g. raw_patients), which this simulated team
    doesn't own and can't fix. Fix instead modifies the FIRST transform
    stage this team DOES own downstream of X (transform/staging_patients.sql)
    — the same split pattern, one hop later, because the real source can't
    be touched.

LLM usage is single-shot generation (`LLMBackend.complete()`), not a
multi-turn agentic loop — a real, structural difference from Investigator,
not an oversight: there's no exploration needed, just "given this real
schema and this finding, generate SQL," checked deterministically
afterward. No Design A/B split needed; `complete()` already works
uniformly across all three backends from Sprint 2.

Validation is 100% deterministic — SQL generated by the model, checked by
code, never by re-asking the model. TWO separate, required passes, added
after Part D's own live run surfaced why one pass isn't enough:

  1. src/codegen/sql_validation.py — runs the candidate SQL against a
     scratch COPY of the real, already-populated healthcare.db, never the
     committed one (Sprint 3 WP1 Part A's own lesson, learned the hard
     way). Answers "does this fix clean the data correctly?"
  2. src/codegen/fresh_build_validation.py — runs the ENTIRE transform
     sequence (staging_patients -> mart_billing -> mart_demographics ->
     claims) against a database seeded with NOTHING but a small real
     raw_patients sample, with the candidate SQL standing in for its one
     stage. Answers a different question a human reviewer actually asks
     before merging a file: "does this file still do everything the old
     file did?" Part D's first live Cigna fix passed pass 1 cleanly while
     silently dropping its own CREATE TABLE statement — the generated file
     could no longer bootstrap on a genuinely fresh database, and pass 1
     had no way to see that, because every db it ever tests against
     already has the table. Fresh-database runnability was a real
     invariant nobody had written down as a check, so nothing guarded it.
     This is the general shape of most escaped bugs: not wrong answers to
     asked questions, but unasked ones.

Both passes must succeed for an attempt to count. Up to 2 retries with the
exact error from whichever pass failed fed back; after that, an honest
failure, no PR.

PR body is a deterministic template built from Incident/InvestigatorFinding
fields — the ONE place free-form model text appears is a single, clearly
marked section quoting `root_cause_summary` verbatim. No fresh LLM prose
writes the PR description itself.
"""

import asyncio
import json
import os
import re
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from dotenv import load_dotenv
from mcp import ClientSession, StdioServerParameters
from mcp.client.stdio import stdio_client

from codegen.fresh_build_validation import FreshBuildResult, fresh_scratch_db, run_fresh_build, seed_fresh_raw_patients
from codegen.sql_validation import ValidationResult, apply_and_validate_fix, scratch_copy
from agents.llm_backend import LLMBackend, LLMBackendError

load_dotenv()

DATAHUB_SERVER = os.environ.get("DATAHUB_GMS_URL", "http://localhost:8080")
DATAHUB_TOKEN = os.environ.get("DATAHUB_GMS_TOKEN")

_MODULE_DIR = Path(__file__).resolve().parent
_REPO_ROOT = _MODULE_DIR.parent.parent

# The real, committed database (decision 0002) -- read-only for schema
# purposes here; every mutation this module makes goes through
# scratch_copy(), never this path directly.
DB_PATH = (_REPO_ROOT / "src" / "datahub" / "healthcare.db").resolve()

# The simulated pipeline-owner repo (Sprint 3 WP2 Part A) -- assumed
# already cloned locally at this path, not re-cloned per run.
DATA_PLATFORM_REPO_PATH = Path(os.environ.get("DATA_PLATFORM_REPO_PATH", str(Path.home() / "projects" / "denial-guardian-data-platform")))
DATA_PLATFORM_REPO_SLUG = os.environ.get("DATA_PLATFORM_REPO_SLUG", "ThakurRanveerSingh/denial-guardian-data-platform")
MAIN_REPO_GITHUB_SLUG = os.environ.get("MAIN_REPO_GITHUB_SLUG", "ThakurRanveerSingh/claims-denial-guardian")

DEFAULT_MAX_RETRIES = 2  # 3 total attempts (1 initial + 2 retries)

# llm_backend.py's DEFAULT_COMPLETE_TIMEOUT_S (60s) was tuned for Sentinel's
# narration seam -- a short, near-empty-context call. Remediator's prompt
# carries real weight (live schema for multiple tables, the full current
# transform SQL, and on a retry, the previous attempt's SQL too) and asks
# for actual reasoning about a real constraint (the dependent-views
# gotcha), not just text generation. Measured directly, twice, against the
# real Cigna incident: a bare `claude -p "..."` sanity call completes in
# ~3s, but this prompt's real generation calls consistently exceeded 120s
# without ever completing. Raised to match DEFAULT_INVESTIGATE_TIMEOUT_S
# (llm_backend.py) -- the existing precedent in this codebase for "a call
# that does real reasoning, not a narration one-liner" -- rather than
# guessing at a new number.
GENERATION_TIMEOUT_S = 240.0


# ---------------------------------------------------------------------------
# Fix-shape selection -- decision 0008.
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class FixTarget:
    """Which file gets modified, which table it builds, and what upstream
    schema context the model needs to see. One of these per
    primary_root_cause prefix -- see _fix_target_for()."""

    transform_file: str      # relative to DATA_PLATFORM_REPO_PATH, e.g. "transform/claims.sql"
    table_name: str          # the table this transform builds, e.g. "claims"
    upstream_tables: tuple   # table names the transform reads FROM, for schema context
    check_column: str = "billing_amount"


FIX_TARGET_CLAIMS = FixTarget(
    transform_file="transform/claims.sql", table_name="claims",
    upstream_tables=("mart_billing", "mart_demographics"),
)
FIX_TARGET_STAGING = FixTarget(
    transform_file="transform/staging_patients.sql", table_name="staging_patients",
    upstream_tables=("raw_patients",),
)


def _fix_target_for(primary_root_cause: str) -> Optional[FixTarget]:
    """`introduced_at:X` -> fix X's own build. `inherited_from:X` -> X
    isn't ours to fix (it's upstream, e.g. raw_patients), so fix the first
    transform stage THIS simulated team owns downstream of it instead —
    staging_patients, not X itself. Returns None for "inconclusive" or any
    other value: there's no fix to generate for a finding with no
    confident root cause.
    """
    if primary_root_cause.startswith("introduced_at:"):
        return FIX_TARGET_CLAIMS
    if primary_root_cause.startswith("inherited_from:"):
        return FIX_TARGET_STAGING
    return None


def _pr_title(primary_root_cause: str, incident_id: str) -> str:
    """Distinct, legible-at-a-glance titles per fix shape (repo owner's
    explicit ask, Part B amendment 2) -- a formatting decision keyed off
    primary_root_cause, not new machinery."""
    if primary_root_cause.startswith("introduced_at:"):
        return f"Guard claims build: quarantine sign-flipped billing ({incident_id})"
    if primary_root_cause.startswith("inherited_from:"):
        return f"Quarantine invalid source billing at staging boundary ({incident_id})"
    return f"Guardian fix ({incident_id})"


# ---------------------------------------------------------------------------
# Result types.
# ---------------------------------------------------------------------------


@dataclass
class RemediationAttempt:
    attempt_number: int
    sql: str
    validation: ValidationResult
    # None when `validation.success` is False -- the fresh-build pass never
    # runs if the cheaper populated-db pass already failed (no point
    # spending the extra work). Both must succeed for the attempt to count.
    fresh_build: Optional[FreshBuildResult] = None


@dataclass
class RemediatorResult:
    incident_id: str
    status: str  # "success" | "failed_validation" | "no_fix_available"
    fix_target: Optional[FixTarget] = None
    attempts: list = field(default_factory=list)  # list[RemediationAttempt]
    pr_url: Optional[str] = None
    pr_already_existed: bool = False
    pr_updated: bool = False  # True only when force=True regenerated an already-open PR in place
    branch_name: Optional[str] = None
    owner: Optional[str] = None
    reason: Optional[str] = None  # human-readable reason for failed/no_fix_available


# ---------------------------------------------------------------------------
# MCP reads (schema + ownership) -- same session-spawning pattern as
# investigator.py/scribe.py, duplicated deliberately (decision 0007's
# Consequences section already states why this codebase doesn't share this
# boilerplate across agent modules).
# ---------------------------------------------------------------------------


async def _call_mcp_tool(session: ClientSession, tool_name: str, arguments: dict) -> dict:
    result = await session.call_tool(tool_name, arguments)
    parts = []
    for block in result.content:
        text = getattr(block, "text", None)
        parts.append(text if text is not None else str(block))
    return json.loads("\n".join(parts))


async def _resolve_entity_urn(session: ClientSession, table_name: str) -> Optional[str]:
    data = await _call_mcp_tool(session, "search", {"query": f"/q {table_name}", "filter": "entity_type = dataset", "num_results": 20})
    for result in data.get("searchResults", []):
        entity = result.get("entity", {})
        if entity.get("properties", {}).get("name") == table_name:
            return entity.get("urn")
    return None


async def _get_entity_details(session: ClientSession, urn: str) -> dict:
    return await _call_mcp_tool(session, "get_entities", {"urns": urn})


def _schema_fields(details: dict) -> list:
    fields = (details.get("schemaMetadata") or {}).get("fields") or []
    return [(f.get("fieldPath"), f.get("nativeDataType")) for f in fields]


def _first_owner_name(details: dict) -> Optional[str]:
    owners = (details.get("ownership") or {}).get("owners") or []
    if not owners:
        return None
    return owners[0].get("owner", {}).get("name")


async def _fetch_schema_and_owner_async(fix_target: FixTarget) -> tuple:
    """Returns (schema_context: dict[table_name, list[(field, type)]], owner: Optional[str]).
    Live MCP reads for the target table and every upstream table it names
    — the prompt handed to the LLM uses ONLY what comes back here, never
    an assumed column list."""
    server_params = StdioServerParameters(
        command="uvx", args=["mcp-server-datahub@latest"],
        env={**os.environ, "DATAHUB_GMS_URL": DATAHUB_SERVER, "DATAHUB_GMS_TOKEN": DATAHUB_TOKEN or ""},
    )
    schema_context = {}
    owner = None
    async with stdio_client(server_params) as (read, write):
        async with ClientSession(read, write) as session:
            await session.initialize()
            for table_name in (fix_target.table_name,) + fix_target.upstream_tables:
                urn = await _resolve_entity_urn(session, table_name)
                if urn is None:
                    continue
                details = await _get_entity_details(session, urn)
                schema_context[table_name] = _schema_fields(details)
                if table_name == fix_target.table_name:
                    owner = _first_owner_name(details)
    return schema_context, owner


def fetch_schema_and_owner(fix_target: FixTarget) -> tuple:
    return asyncio.run(_fetch_schema_and_owner_async(fix_target))


# ---------------------------------------------------------------------------
# Prompt construction and SQL extraction.
# ---------------------------------------------------------------------------


_FENCED_SQL_RE = re.compile(r"```sql\s*(.*?)\s*```", re.DOTALL)


def _extract_sql(text: str) -> str:
    """Pull the LAST fenced ```sql``` block out of the model's response --
    same "last, not first" reasoning as investigator.py's
    _extract_fenced_json (a model that second-guesses itself mid-answer
    may show an earlier draft before its real final answer). Raises
    ValueError if none found, which the retry loop turns into an
    honest failed attempt, not a crash.
    """
    matches = _FENCED_SQL_RE.findall(text or "")
    if not matches:
        raise ValueError("no fenced ```sql``` block found in the model's response")
    return matches[-1].strip()


def _format_schema(schema_context: dict) -> str:
    lines = []
    for table_name, fields in schema_context.items():
        lines.append(f"{table_name}:")
        for field_path, native_type in fields:
            lines.append(f"  {field_path} {native_type}")
    return "\n".join(lines)


def _build_fix_prompt(
    finding, fix_target: FixTarget, current_sql: str, schema_context: dict,
    *, previous_sql: Optional[str] = None, previous_error: Optional[str] = None,
) -> str:
    lines = [
        "You are Remediator, an agent that generates a fix SQL script for a data-quality",
        "defect an investigation has already found and explained.",
        "",
        f"Investigator's finding: {finding.primary_root_cause}",
        f"Root cause summary: {finding.root_cause_summary}",
        "",
        "Live, current schema (read from DataHub, not assumed):",
        _format_schema(schema_context),
        "",
        f"Current build SQL for `{fix_target.table_name}` (from the pipeline-owner's own repo):",
        "```sql",
        current_sql.strip(),
        "```",
        "",
        "Task: rewrite this into a fix SQL script that QUARANTINES rows",
        f"violating `{fix_target.check_column} >= 0` instead of letting them land in",
        f"`{fix_target.table_name}` unexamined. Do NOT correct or alter any values",
        "(e.g. do not use ABS() or flip a sign) -- the cause of the violation is not",
        "established well enough to assume a correction is safe. Requirements:",
        "",
        f"1. Build a `{fix_target.table_name}_quarantine` table (same columns as",
        f"   `{fix_target.table_name}`) containing exactly the rows that violate",
        f"   `{fix_target.check_column} >= 0` (or are NULL/unparseable, if the column is",
        "   text -- treat anything that cannot be evaluated as >= 0 as a violation too),",
        "   using the SAME upstream source(s) and derivation logic as the current build",
        "   SQL above.",
        f"2. Rebuild `{fix_target.table_name}` itself with only the clean rows, using that",
        "   SAME upstream derivation.",
        "3. This file will be validated TWICE: once against a database that already has",
        f"   real data in `{fix_target.table_name}` (does the fix clean it correctly?), and",
        "   once against a COMPLETELY FRESH, EMPTY database that has never had",
        f"   `{fix_target.table_name}` or `{fix_target.table_name}_quarantine` created at all",
        "   (does this file still work as a from-scratch build script, the same job the",
        "   ORIGINAL file above did?). Both must pass. This means:",
        "   - Do NOT DROP the table to rebuild it. Some tables in this database have other",
        "     SQL VIEWS defined against them elsewhere; a DROP + CREATE-replacement + RENAME",
        "     sequence leaves those views unable to resolve the table for a moment",
        "     mid-script and fails the whole script, even though the end state would have",
        "     been fine.",
        "   - Do NOT assume the table already exists either (e.g. a bare `DELETE FROM",
        f"     {fix_target.table_name}` with no CREATE anywhere fails outright on a fresh",
        "     database).",
        "   - The pattern that satisfies both constraints at once: `CREATE TABLE IF NOT",
        "     EXISTS` the table using a `SELECT ... WHERE 0` (a real SQLite idiom -- this",
        "     creates the correct columns with zero rows if the table doesn't exist yet,",
        "     and does nothing at all if it already does), THEN `DELETE FROM` it and",
        "     `INSERT INTO` it with the real, filtered rows. Worked example for a table",
        "     `t` built from `SELECT cols FROM upstream`:",
        "     ```sql",
        "     CREATE TABLE IF NOT EXISTS t AS SELECT cols FROM upstream WHERE 0;",
        "     DELETE FROM t;",
        "     INSERT INTO t SELECT cols FROM upstream WHERE <clean condition>;",
        "     ```",
        "     Apply this SAME pattern to BOTH the quarantine table and the main table.",
        "4. Every row implied by the original derivation must end up in EXACTLY ONE of",
        f"   the two places (`{fix_target.table_name}` or `{fix_target.table_name}_quarantine`)",
        "   -- nothing dropped, nothing duplicated.",
        "5. Keep the ORIGINAL file's header comment (the lineage/design-rationale notes",
        "   shown at the top of the current build SQL above) -- APPEND your own comment",
        "   explaining the quarantine fix underneath it, do not delete or replace it. A",
        "   future engineer reading this file still needs to know WHY the original design",
        "   choices were made, not just what this fix changed.",
        "",
        "Respond with ONLY one fenced ```sql``` code block containing the complete,",
        "runnable SQL script (may be multiple statements) -- no prose outside the block.",
    ]
    if previous_sql:
        lines += [
            "",
            "Your previous attempt failed. Previous SQL:",
            "```sql",
            previous_sql,
            "```",
            f"Failure reason: {previous_error}",
            "Fix the issue and try again.",
        ]
    elif previous_error is not None:
        # Extraction itself failed last time (no fenced ```sql``` block found,
        # or the backend call errored) -- there is no previous SQL worth
        # showing, only the reason to avoid repeating it.
        lines += [
            "",
            f"Your previous attempt failed before producing usable SQL: {previous_error}",
            "Make sure your response contains exactly one fenced ```sql``` code block.",
        ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Retry loop.
# ---------------------------------------------------------------------------


def _generate_and_validate(
    backend: LLMBackend, finding, fix_target: FixTarget, current_sql: str, schema_context: dict,
    healthcare_db_path: Path, data_platform_repo_path: Path, max_retries: int = DEFAULT_MAX_RETRIES,
) -> tuple:
    """Returns (attempts: list[RemediationAttempt], final_success: bool).
    An attempt only counts as success when BOTH validation passes succeed
    -- see the module docstring for why a single pass (correct-on-top-of-
    already-populated-data) isn't the same question as "would I merge this
    file," and missed exactly that during Part D's own live run."""
    attempts = []
    previous_sql, previous_error = None, None

    for attempt_num in range(1, max_retries + 2):  # 1, 2, 3 for max_retries=2
        prompt = _build_fix_prompt(
            finding, fix_target, current_sql, schema_context,
            previous_sql=previous_sql, previous_error=previous_error,
        )
        try:
            completion = backend.complete([{"role": "user", "content": prompt}], max_tokens=4096, timeout_s=GENERATION_TIMEOUT_S)
            sql = _extract_sql(completion.text)
        except (LLMBackendError, ValueError) as e:
            validation = ValidationResult(success=False, original_count=0, error=str(e))
            attempts.append(RemediationAttempt(attempt_number=attempt_num, sql="", validation=validation))
            previous_sql, previous_error = "", str(e)
            continue

        with scratch_copy(healthcare_db_path) as scratch_path:
            validation = apply_and_validate_fix(
                scratch_path, sql,
                original_table=fix_target.table_name, clean_table=fix_target.table_name,
                quarantine_table=f"{fix_target.table_name}_quarantine", check_column=fix_target.check_column,
            )

        if not validation.success:
            attempts.append(RemediationAttempt(attempt_number=attempt_num, sql=sql, validation=validation))
            previous_sql = sql
            previous_error = validation.error or (
                f"validation failed: {validation.violation_count_in_clean} rows still violate "
                f"the check in the clean table, or conservation failed "
                f"(clean={validation.clean_count}, quarantine={validation.quarantine_count}, "
                f"original={validation.original_count})"
            )
            continue

        # Pass 1 succeeded -- now the harder question: does this file still
        # work as a from-scratch build, not just on top of data pass 1's
        # own scratch copy already had?
        with fresh_scratch_db() as fresh_path:
            seed_fresh_raw_patients(fresh_path, healthcare_db_path)
            fresh_build = run_fresh_build(
                fresh_path, fix_target.table_name, sql, data_platform_repo_path, check_column=fix_target.check_column,
            )

        attempts.append(RemediationAttempt(attempt_number=attempt_num, sql=sql, validation=validation, fresh_build=fresh_build))

        if fresh_build.success:
            return attempts, True

        previous_sql = sql
        if fresh_build.failed_stage is not None:
            previous_error = (
                f"fresh-database build failed at the '{fresh_build.failed_stage}' stage "
                f"(this file must still work as a from-scratch build, not just against a "
                f"database that already has data in it): {fresh_build.error}"
            )
        else:
            previous_error = (
                f"the fix ran on a fresh database without a SQL error, but "
                f"{fresh_build.violation_count_in_clean} rows still violate the check in "
                f"the clean table -- the fresh-database branch of this script is producing "
                f"different results than intended"
            )

    return attempts, False


# ---------------------------------------------------------------------------
# PR body / branch naming, and git/gh mechanics.
# ---------------------------------------------------------------------------


def _branch_name_for(incident_id: str) -> str:
    return f"guardian/fix-{incident_id.lower()}"


def _incident_github_url(incident_id: str) -> str:
    return f"https://github.com/{MAIN_REPO_GITHUB_SLUG}/blob/main/examples/{incident_id}/incident.json"


def _build_pr_body(
    incident_id: str, sentinel_finding, finding, fix_target: FixTarget, sql: str,
    validation: ValidationResult, fresh_build: Optional[FreshBuildResult], owner: Optional[str],
) -> str:
    segment = sentinel_finding.segment
    conservation = "PASS" if validation.conserves_rows else "FAIL"
    owner_line = owner or "unknown — not found in DataHub ownership metadata"
    fresh_build_line = "PASS" if (fresh_build is not None and fresh_build.success) else "not run"

    return f"""## Guardian-generated fix

**Incident**: `{incident_id}`
**Segment**: {segment.insurance_provider} / {segment.medical_condition} (z = {sentinel_finding.z_score:.2f})
**Root cause**: `{finding.primary_root_cause}`
**Confidence**: {finding.confidence}

## What changed

`{fix_target.transform_file}` now splits rows at build time: clean rows
(`{fix_target.check_column} >= 0`) continue to `{fix_target.table_name}` as
before; violating rows are routed to a new
`{fix_target.table_name}_quarantine` table instead of silently landing in
`{fix_target.table_name}`.

## Why quarantine, not correction

The tempting fix here would be to correct the values directly (e.g.
`ABS({fix_target.check_column})`) and make the anomaly disappear. This PR
does not do that: **we don't actually know the cause of the violation, and
in health insurance, silently "fixing" financial data you don't understand
is exactly how a data team creates the next wrongful-denial incident while
erasing the evidence of this one.** Clean rows flow, suspect rows are
routed to `{fix_target.table_name}_quarantine` for a human to review,
nothing is invented. Guardian never pretends to know more than the
evidence supports.

## Validation (deterministic, two required passes — never the real database)

Pass 1 — does the fix clean the data correctly? (scratch COPY of the real,
already-populated healthcare.db)

| Check | Result |
|---|---|
| Original `{fix_target.table_name}` row count | {validation.original_count} |
| Clean rows after fix | {validation.clean_count} |
| **Quarantined rows** | **{validation.quarantine_count}** |
| Violations remaining in clean table (must be 0) | {validation.violation_count_in_clean} |
| Conservation (clean + quarantined == original) | {conservation} |

Pass 2 — does this file still work as a from-scratch build script, the
same job the original file did? (a genuinely fresh database, seeded with
nothing but a small real `raw_patients` sample, run through the ENTIRE
transform sequence)

| Check | Result |
|---|---|
| Fresh-database build | {fresh_build_line} |

## Operational note

Rows in `{fix_target.table_name}_quarantine` require human review — suggested
owner: **{owner_line}** (read live from DataHub ownership metadata).

## Investigator's Finding (verbatim)

> {finding.root_cause_summary}

## Generated fix SQL

```sql
{sql}
```

Full incident record: {_incident_github_url(incident_id)}
"""


def _run_git(args: list, cwd: Path) -> subprocess.CompletedProcess:
    return subprocess.run(["git"] + args, cwd=str(cwd), capture_output=True, text=True, timeout=30)


def _existing_pr_url(branch_name: str) -> Optional[str]:
    """Deliberately does NOT use `gh ... --jq '.[0].url'`: jq's `.[0]` on an
    empty JSON array evaluates to `null`, and `.url` on `null` is also
    `null` — jq's default text output for that is the 4-character string
    `"null"`, not empty stdout. A naive `.strip() or None` on that would
    read as "an existing PR was found" (truthy non-empty string) when
    there genuinely isn't one, breaking idempotency in exactly the case it
    exists to handle. Parsing the JSON array directly sidesteps that
    footgun entirely.
    """
    result = subprocess.run(
        ["gh", "pr", "list", "--repo", DATA_PLATFORM_REPO_SLUG, "--head", branch_name, "--json", "url"],
        capture_output=True, text=True, timeout=30,
    )
    if result.returncode != 0:
        return None
    try:
        prs = json.loads(result.stdout or "[]")
    except json.JSONDecodeError:
        return None
    return prs[0]["url"] if prs else None


def _read_committed_file(repo_path: Path, relative_file: str, ref: str = "origin/main") -> str:
    """Read a file's content as committed on `ref`, NOT from the local
    working tree. `_open_pr` leaves the working tree checked out on
    whichever branch it last created/updated (`git checkout -B`) — reading
    straight off disk risks showing the model a stale or already-fixed
    version of the file instead of the true current original, depending on
    what an earlier run happened to leave checked out. `git show` reads
    the committed blob directly and is unaffected by the working tree's
    current state."""
    result = subprocess.run(
        ["git", "show", f"{ref}:{relative_file}"], cwd=str(repo_path), capture_output=True, text=True, timeout=10,
    )
    if result.returncode != 0:
        raise RuntimeError(f"failed to read {relative_file} from {ref}: {result.stderr}")
    return result.stdout


def _open_pr(fix_target: FixTarget, sql: str, title: str, body: str, incident_id: str, branch_name: str, *, force: bool = False) -> tuple:
    """Returns (pr_url, already_existed, updated). Takes `branch_name` from
    the caller rather than recomputing it, since run_remediator() already
    checked it for an existing PR before ever generating anything — this
    function's own check (below) is defense-in-depth against a race (e.g.
    two runs overlapping), not the primary idempotency guard; see
    run_remediator()'s docstring for why the primary check had to move
    earlier than this function.

    `force`: when an existing PR is found AND force=True, push an updated
    commit onto that SAME branch (advancing it, not rewriting it) and
    `gh pr edit` its title/body, instead of short-circuiting. Used when the
    fix criteria itself changed (e.g. a new validation pass was added) and
    an already-open PR needs to be regenerated in place, not left stale
    and not duplicated into a second PR for the same incident.
    """
    existing = _existing_pr_url(branch_name)
    if existing and not force:
        return existing, True, False

    repo = DATA_PLATFORM_REPO_PATH
    _run_git(["fetch", "origin", "main"], cwd=repo)

    if existing and force:
        # Advance the EXISTING branch with a new commit on top, not a
        # rebuild off main -- a plain new commit is the less disruptive way
        # to update a PR a reviewer may already be looking at, versus
        # rewriting history underneath them.
        _run_git(["fetch", "origin", branch_name], cwd=repo)
        checkout = _run_git(["checkout", "-B", branch_name, f"origin/{branch_name}"], cwd=repo)
    else:
        checkout = _run_git(["checkout", "-B", branch_name, "origin/main"], cwd=repo)
    if checkout.returncode != 0:
        raise RuntimeError(f"git checkout -B {branch_name} failed: {checkout.stderr}")

    target_path = repo / fix_target.transform_file
    target_path.write_text(sql.rstrip() + "\n")

    _run_git(["add", fix_target.transform_file], cwd=repo)
    commit_subject = f"Update fix: {title}" if (existing and force) else title
    commit = _run_git(
        ["commit", "-m", f"{commit_subject}\n\nGenerated by Guardian's Remediator. See PR body for validation results."], cwd=repo,
    )
    if commit.returncode != 0:
        raise RuntimeError(f"git commit failed: {commit.stderr}")

    push = _run_git(["push", "-u", "origin", branch_name, "--force-with-lease"], cwd=repo)
    if push.returncode != 0:
        # --force-with-lease fails cleanly if the remote branch doesn't
        # exist yet (nothing to lease against), OR if it does exist but the
        # local ref just fetched isn't its current tip for some reason --
        # retry a plain push once.
        push = _run_git(["push", "-u", "origin", branch_name], cwd=repo)
        if push.returncode != 0:
            raise RuntimeError(f"git push failed: {push.stderr}")

    if existing and force:
        edit_result = subprocess.run(
            ["gh", "pr", "edit", existing, "--repo", DATA_PLATFORM_REPO_SLUG, "--title", title, "--body", body],
            capture_output=True, text=True, timeout=60,
        )
        if edit_result.returncode != 0:
            raise RuntimeError(f"gh pr edit failed: {edit_result.stderr}")
        return existing, True, True

    pr_result = subprocess.run(
        ["gh", "pr", "create", "--repo", DATA_PLATFORM_REPO_SLUG, "--title", title, "--body", body, "--head", branch_name, "--base", "main"],
        capture_output=True, text=True, timeout=60,
    )
    if pr_result.returncode != 0:
        raise RuntimeError(f"gh pr create failed: {pr_result.stderr}")

    pr_url = pr_result.stdout.strip().splitlines()[-1] if pr_result.stdout.strip() else None
    if not pr_url:
        raise RuntimeError(f"gh pr create produced no URL. stdout={pr_result.stdout!r}")
    return pr_url, False, False


# ---------------------------------------------------------------------------
# Orchestration.
# ---------------------------------------------------------------------------


def run_remediator(
    incident, backend: LLMBackend, *,
    healthcare_db_path: Path = DB_PATH, data_platform_repo_path: Path = DATA_PLATFORM_REPO_PATH, force: bool = False,
) -> RemediatorResult:
    """Top-level entry point, matching sentinel.py/investigator.py/
    scribe.py's run_<agent>() naming convention. `incident` is an
    Incident (src/agents/orchestrator.py) with a confident (non-inconclusive)
    InvestigatorFinding — callers check this before calling, same as
    Scribe's own "nothing to do" short-circuit.

    Idempotency check happens HERE, before any LLM call or DataHub read —
    not only inside _open_pr. A branch name is a pure function of
    incident_id alone (_branch_name_for), so "does a PR already exist for
    this incident" can be answered before fix_target, schema, or a single
    token of generation is needed. Checking only inside _open_pr (an
    earlier version of this function did exactly that) would still have
    prevented a duplicate PR, but would keep paying for a real LLM call and
    live DataHub reads on every rerun — the actual expensive part of a
    repeat run, not the git/PR mechanics.

    `force`: skip that short-circuit and regenerate even when a PR already
    exists, pushing the update onto the SAME branch (_open_pr's own
    `force=` path) rather than opening a second PR for the same incident.
    For the one real, deliberate reason this exists: the fix criteria
    itself changed (e.g. fresh_build_validation.py was added after the
    first PRs already existed) and an already-open PR needs to be redone,
    not silently left stale.
    """
    finding = incident.investigator
    if finding is None or finding.primary_root_cause == "inconclusive":
        return RemediatorResult(incident_id=incident.incident_id, status="no_fix_available", reason="no confident InvestigatorFinding to remediate")

    fix_target = _fix_target_for(finding.primary_root_cause)
    if fix_target is None:
        return RemediatorResult(incident_id=incident.incident_id, status="no_fix_available", reason=f"no known fix shape for primary_root_cause={finding.primary_root_cause!r}")

    branch_name = _branch_name_for(incident.incident_id)
    existing_pr_url = _existing_pr_url(branch_name)
    if existing_pr_url and not force:
        return RemediatorResult(
            incident_id=incident.incident_id, status="success", fix_target=fix_target,
            pr_url=existing_pr_url, pr_already_existed=True, branch_name=branch_name,
        )

    # A PREVIOUS run's _open_pr() may have left the working tree checked
    # out on some other incident's guardian/fix-* branch (git checkout -B
    # switches it and never switches back). run_fresh_build (inside
    # _generate_and_validate below) reads the OTHER 3 transform files
    # straight off disk, not via git -- resetting to origin/main here,
    # before any file read happens, guarantees every stage's "real,
    # unmodified" content is actually main's, not whatever a prior branch
    # happened to leave checked out. _read_committed_file for the fix's
    # OWN file is already immune to this (reads the git blob directly),
    # but the other 3 files aren't, so the working tree itself needs to be
    # put in a known-good state too.
    _run_git(["fetch", "origin", "main"], cwd=data_platform_repo_path)
    checkout_main = _run_git(["checkout", "-B", "main", "origin/main"], cwd=data_platform_repo_path)
    if checkout_main.returncode != 0:
        raise RuntimeError(f"git checkout -B main origin/main failed: {checkout_main.stderr}")

    current_sql = _read_committed_file(data_platform_repo_path, fix_target.transform_file)
    schema_context, owner = fetch_schema_and_owner(fix_target)

    attempts, success = _generate_and_validate(
        backend, finding, fix_target, current_sql, schema_context, healthcare_db_path, data_platform_repo_path,
    )

    if not success:
        return RemediatorResult(
            incident_id=incident.incident_id, status="failed_validation", fix_target=fix_target,
            attempts=attempts, owner=owner,
            reason=f"all {len(attempts)} attempt(s) failed validation",
        )

    final_attempt = attempts[-1]
    title = _pr_title(finding.primary_root_cause, incident.incident_id)
    body = _build_pr_body(
        incident.incident_id, incident.sentinel, finding, fix_target,
        final_attempt.sql, final_attempt.validation, final_attempt.fresh_build, owner,
    )

    pr_url, already_existed, updated = _open_pr(fix_target, final_attempt.sql, title, body, incident.incident_id, branch_name, force=force)

    return RemediatorResult(
        incident_id=incident.incident_id, status="success", fix_target=fix_target,
        attempts=attempts, pr_url=pr_url, pr_already_existed=already_existed, pr_updated=updated,
        branch_name=branch_name, owner=owner,
    )
